name: Android CI

on:
  [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
    - name: Install correct NDK
      run: sdkmanager "ndk;21.3.6528147"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :teamcode:build
